In [19]:
import pandas as pd
import numpy as np
import seaborn as sns

In [20]:
df = pd.read_csv("titanic.csv")

In [21]:
df

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.0000,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.4500,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.7500,NaN,Q

In [22]:
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [23]:
df.head(5)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [24]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [25]:
df.drop(columns=["PassengerId","SibSp","Parch","Pclass","Embarked"],inplace=True)

In [26]:
df

,Survived,Name,Sex,Age,Ticket,Fare,Cabin
0,0,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85
2,1,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123
4,0,"Allen, Mr. William Henry",male,35.0,373450,8.0500,NaN
...,...,...,...,...,...,...,...
886,0,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,NaN
887,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42
888,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,W./C. 6607,23.4500,NaN
889,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148
890,0,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,NaN

In [27]:
df.head(4)

,Survived,Name,Sex,Age,Ticket,Fare,Cabin
0,0,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,NaN
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85
2,1,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,NaN
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123

In [28]:
df.isnull().sum()

Survived      0
Name          0
Sex           0
Age         177
Ticket        0
Fare          0
Cabin       687
dtype: int64

In [29]:
df["Age"] = df["Age"].fillna(df["Age"].median())

In [30]:
df["Cabin"] = df["Cabin"].fillna("Unknown")

In [31]:
df.isnull().sum()

Survived    0
Name        0
Sex         0
Age         0
Ticket      0
Fare        0
Cabin       0
dtype: int64

In [32]:
df

,Survived,Name,Sex,Age,Ticket,Fare,Cabin
0,0,"Braund, Mr. Owen Harris",male,22.0,A/5 21171,7.2500,Unknown
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,PC 17599,71.2833,C85
2,1,"Heikkinen, Miss. Laina",female,26.0,STON/O2. 3101282,7.9250,Unknown
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,113803,53.1000,C123
4,0,"Allen, Mr. William Henry",male,35.0,373450,8.0500,Unknown
...,...,...,...,...,...,...,...
886,0,"Montvila, Rev. Juozas",male,27.0,211536,13.0000,Unknown
887,1,"Graham, Miss. Margaret Edith",female,19.0,112053,30.0000,B42
888,0,"Johnston, Miss. Catherine Helen ""Carrie""",female,28.0,W./C. 6607,23.4500,Unknown
889,1,"Behr, Mr. Karl Howell",male,26.0,111369,30.0000,C148
890,0,"Dooley, Mr. Patrick",male,32.0,370376,7.7500,Unknown

In [34]:
df = pd.get_dummies(df,columns=["Sex"],drop_first=True,dtype="int64")

In [35]:
df.head()

,Survived,Name,Age,Ticket,Fare,Cabin,Sex_male
0,0,"Braund, Mr. Owen Harris",22.0,A/5 21171,7.2500,Unknown,1
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,71.2833,C85,0
2,1,"Heikkinen, Miss. Laina",26.0,STON/O2. 3101282,7.9250,Unknown,0
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,53.1000,C123,0
4,0,"Allen, Mr. William Henry",35.0,373450,8.0500,Unknown,1

In [36]:
print(df.head())
print(df.shape)
print(df.dtypes)

   Survived                                               Name   Age  \
0         0                            Braund, Mr. Owen Harris  22.0
1         1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0
2         1                             Heikkinen, Miss. Laina  26.0
3         1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0
4         0                           Allen, Mr. William Henry  35.0

             Ticket     Fare    Cabin  Sex_male
0         A/5 21171   7.2500  Unknown         1
1          PC 17599  71.2833      C85         0
2  STON/O2. 3101282   7.9250  Unknown         0
3            113803  53.1000     C123         0
4            373450   8.0500  Unknown         1
(891, 7)
Survived      int64
Name         object
Age         float64
Ticket       object
Fare        float64
Cabin        object
Sex_male      int64
dtype: object

In [37]:
print("Duplicates before cleaning:", df.duplicated().sum())

df.drop_duplicates(inplace=True)

print("Duplicates after cleaning:", df.duplicated().sum())

Duplicates before cleaning: 0
Duplicates after cleaning: 0

In [38]:
df

,Survived,Name,Age,Ticket,Fare,Cabin,Sex_male
0,0,"Braund, Mr. Owen Harris",22.0,A/5 21171,7.2500,Unknown,1
1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",38.0,PC 17599,71.2833,C85,0
2,1,"Heikkinen, Miss. Laina",26.0,STON/O2. 3101282,7.9250,Unknown,0
3,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",35.0,113803,53.1000,C123,0
4,0,"Allen, Mr. William Henry",35.0,373450,8.0500,Unknown,1
...,...,...,...,...,...,...,...
886,0,"Montvila, Rev. Juozas",27.0,211536,13.0000,Unknown,1
887,1,"Graham, Miss. Margaret Edith",19.0,112053,30.0000,B42,0
888,0,"Johnston, Miss. Catherine Helen ""Carrie""",28.0,W./C. 6607,23.4500,Unknown,0
889,1,"Behr, Mr. Karl Howell",26.0,111369,30.0000,C148,1
890,0,"Dooley, Mr. Patrick",32.0,370376,7.7500,Unknown,1

In [39]:
df.to_csv("titanic_cleaned.csv", index=False)

from google.colab import files
files.download("titanic_cleaned.csv")

In [40]:
report = pd.DataFrame({
    "Data Type": df.dtypes.astype(str),
    "Missing Values": df.isnull().sum(),
    "Unique Values": df.nunique()
})

display(report)

print("Final rows and columns:", df.shape)
print("Remaining duplicate rows:", df.duplicated().sum())
print("Total missing cells:", df.isnull().sum().sum())

report.to_csv("data_quality_report_after.csv")
files.download("data_quality_report_after.csv")

         Data Type  Missing Values  Unique Values
Survived     int64               0              2
Name        object               0            891
Age        float64               0             88
Ticket      object               0            681
Fare       float64               0            248
Cabin       object               0            148
Sex_male     int64               0              2

Final rows and columns: (891, 7)
Remaining duplicate rows: 0
Total missing cells: 0